# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025-2026 NVIDIA Corporation

"""CLI front-end for ``alpasim_utils.lanelet2_to_clipgt``.

Convert an Autoware Lanelet2 ``.osm`` file into a ClipGT parquet bundle that
Alpasim's map loader (``trajdata.populate_vector_map``) can ingest.

Examples
--------
MGRS grid with metre offset (autoware_lanelet2_to_opendrive convention)::

    lanelet2-to-clipgt \\
        --osm path/to/lanelet2_map.osm \\
        --output-dir out/clipgt \\
        --mgrs-grid 54SUE \\
        --offset-x 81655.73 --offset-y 50137.43 --offset-z 42.5

Lat/lon::

    lanelet2-to-clipgt --osm map.osm --output-dir out/clipgt \\
        --lat 35.6895 --lon 139.6917 --alt 42.5
"""

from __future__ import annotations

import argparse
import logging
import sys

from alpasim_utils.lanelet2_to_clipgt import (
    DEFAULT_LIB_GIT_URL,
    DEFAULT_LIB_REF,
    DEFAULT_PYTHON,
    LatLonOrigin,
    MgrsOrigin,
    convert_osm_to_clipgt_dir,
)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--osm", required=True, help="Path to the input Autoware Lanelet2 .osm map."
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory the ClipGT parquet bundle is written to.",
    )

    origin = parser.add_argument_group(
        "origin",
        "Map origin in either MGRS or lat/lon form (exactly one form required).",
    )
    origin.add_argument(
        "--mgrs-grid", help="MGRS grid code (e.g. 54SUE or 54SUE815501)."
    )
    origin.add_argument(
        "--offset-x",
        type=float,
        help="Easting offset (metres) inside the MGRS grid square.",
    )
    origin.add_argument(
        "--offset-y",
        type=float,
        help="Northing offset (metres) inside the MGRS grid square.",
    )
    origin.add_argument(
        "--offset-z", type=float, default=0.0, help="Altitude offset (metres)."
    )
    origin.add_argument("--lat", type=float, help="Origin latitude in degrees.")
    origin.add_argument("--lon", type=float, help="Origin longitude in degrees.")
    origin.add_argument(
        "--alt", type=float, default=0.0, help="Origin altitude in metres."
    )

    parser.add_argument(
        "--clip-id",
        help="Optional clip identifier stamped into the parquet keys. Defaults "
        "to a UUID generated by the upstream converter.",
    )
    parser.add_argument(
        "--library-git-url",
        default=DEFAULT_LIB_GIT_URL,
        help="Git URL used by uvx to fetch autoware_lanelet2_to_clipgt.",
    )
    parser.add_argument(
        "--library-ref",
        default=DEFAULT_LIB_REF,
        help="Git ref (branch / tag / commit) of autoware_lanelet2_to_clipgt to use.",
    )
    parser.add_argument(
        "--python",
        default=DEFAULT_PYTHON,
        help="Python version uvx should provision for the converter (default 3.10).",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Enable INFO-level logging."
    )
    return parser


def _origin_from_args(args: argparse.Namespace) -> LatLonOrigin | MgrsOrigin:
    has_latlon = args.lat is not None and args.lon is not None
    has_mgrs = args.mgrs_grid is not None
    if has_latlon == has_mgrs:
        raise SystemExit(
            "error: specify exactly one origin form -- either --mgrs-grid (with "
            "optional offsets) or --lat/--lon."
        )
    if has_latlon:
        return LatLonOrigin(latitude=args.lat, longitude=args.lon, altitude=args.alt)
    if (args.offset_x is None) != (args.offset_y is None):
        raise SystemExit("error: --offset-x and --offset-y must be provided together.")
    return MgrsOrigin(
        grid=args.mgrs_grid,
        offset_x=args.offset_x,
        offset_y=args.offset_y,
        offset_z=args.offset_z,
    )


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    logging.basicConfig(
        level=logging.INFO if args.verbose else logging.WARNING,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    origin = _origin_from_args(args)
    out = convert_osm_to_clipgt_dir(
        args.osm,
        args.output_dir,
        origin,
        clip_id=args.clip_id,
        library_git_url=args.library_git_url,
        library_ref=args.library_ref,
        python_version=args.python,
    )
    print(f"Wrote ClipGT bundle to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
