# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025-2026 NVIDIA Corporation

"""
Defines the omegaconf .yaml configuration format for Alpasim runtime.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict

from alpasim_utils.scenario import VehicleConfig
from omegaconf import MISSING

BASE_SERVICE_NAMES = (
    "driver",
    "physics",
    "trafficsim",
    "controller",
)
CORE_SERVICE_NAMES = (*BASE_SERVICE_NAMES, "renderer")


@dataclass
class UsdzProviderConfig:
    """Configuration for the USDZ artifact-backed scene provider."""

    data_dir: str | None = None
    # Max worker-local USDZ artifact cache size.
    # None = unlimited, 0 = disable cache and always reload artifacts.
    artifact_cache_size: int | None = None


@dataclass
class TrajdataDatasetConfig:
    """Configuration for a single trajdata dataset source."""

    name: str | None = None
    data_dir: str | None = None
    extra_params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TrajdataProviderConfig:
    """Configuration for a trajdata-backed scene provider."""

    cache_location: str = MISSING
    desired_dt: float = 0.1
    load_vector_map: bool = True
    rebuild_cache: bool = False
    rebuild_maps: bool = False
    num_workers: int = 1
    dataset: TrajdataDatasetConfig | None = None


@dataclass
class SceneProviderConfig:
    """Runtime scene provider configuration for one backend family."""

    kind: str = "usdz"  # Literal["usdz", "trajdata"]
    usdz: UsdzProviderConfig | None = field(default_factory=UsdzProviderConfig)
    trajdata: TrajdataProviderConfig | None = None


@dataclass
class SingleUserEndpointConfig:
    """
    Configuration parameters for an endpoint *set by the user* - in contrast to
    addresses which are usually autogenerated by wizard.
    """

    skip: bool = False
    n_concurrent_rollouts: int = 0


@dataclass
class ServiceEndpoint:
    """A service endpoint address with deployment ownership metadata."""

    address: str = MISSING
    managed: bool = True


@dataclass
class EndpointAddresses:
    """A list of URLs for a single endpoint, usually autogenerated by wizard."""

    endpoints: list[ServiceEndpoint] = MISSING


@dataclass
class NetworkSimulatorConfig:
    """
    Addresses of all endpoints in simulation - this section is usually autogenerated by
    wizard.
    """

    driver: EndpointAddresses = MISSING
    physics: EndpointAddresses = MISSING
    trafficsim: EndpointAddresses = MISSING
    controller: EndpointAddresses = MISSING
    renderer: EndpointAddresses = MISSING


@dataclass
class VideoModelConfig:
    """Configuration for the video model renderer."""

    fps: int = 30
    # Chunk sizes must match the external server's --num_frames_per_block and
    # initial-frame contract. Config group chunking/<N>frame.yaml keeps these
    # in sync for the common 8/12/16-frame variants.
    first_chunk_frames: int = 5
    chunk_frames: int = 8
    text_prompt_positive: str = ""
    text_prompt_negative: str = ""

    # Request debug streams from the video model server. Forwarding them to the
    # driver is opt-in because most policies expect RGB camera inputs only.
    return_hdmap_frames: bool = False
    forward_hdmap_to_driver: bool = False

    # "all" forwards every generated frame to the driver. "subsample" forwards
    # the nearest frames matching subsample_count/subsample_interval_us within
    # each returned chunk. Prefer driver.inference.subsample_factor for policy
    # input-rate matching because it operates on the continuous frame cache.
    frame_forwarding_mode: str = "all"
    subsample_count: int = 4
    subsample_interval_us: int = 100_000

    def __post_init__(self) -> None:
        # Numeric guards: fps=0 trips ZeroDivisionError in
        # VideoModelService.__init__ (1_000_000 // config.fps); zero or
        # negative chunk sizes break trajectory building.
        if self.fps <= 0:
            raise ValueError(f"fps must be positive, got {self.fps}")
        if self.first_chunk_frames <= 0:
            raise ValueError(
                f"first_chunk_frames must be positive, got {self.first_chunk_frames}"
            )
        if self.chunk_frames <= 0:
            raise ValueError(f"chunk_frames must be positive, got {self.chunk_frames}")
        if self.forward_hdmap_to_driver and not self.return_hdmap_frames:
            raise ValueError(
                "forward_hdmap_to_driver=True requires return_hdmap_frames=True."
            )
        if self.frame_forwarding_mode not in {"all", "subsample"}:
            raise ValueError(
                f"frame_forwarding_mode must be 'all' or 'subsample', "
                f"got {self.frame_forwarding_mode!r}"
            )


class RendererKind(Enum):
    sensorsim = "sensorsim"
    video_model = "video_model"


@dataclass
class RendererConfig:
    """Configuration for the active renderer implementation."""

    kind: RendererKind = MISSING
    video_model_config: VideoModelConfig | None = None


@dataclass
class RuntimeCameraConfig:
    """Configuration for a camera in the runtime. See `RuntimeCamera` for more details."""

    logical_id: str = "camera_front_wide_120fov"
    height: int = 160
    width: int = 256
    frame_interval_us: int = 33_000  # about 30fps
    shutter_duration_us: int = 17_000


@dataclass
class RuntimeLidarConfig:
    """Configuration for a LiDAR in the runtime. See `RuntimeLidar` for more details.

    ``device_type`` names one of the sensorsim ``LidarDeviceType`` enum members
    (e.g. ``"PANDAR128"`` or ``"AT128"``). It is stored as a string so the
    config file stays free of gRPC-generated enum imports; the runtime maps it
    to the enum when the ``RuntimeLidar`` is built.
    """

    logical_id: str = "lidar_top"
    device_type: str = "PANDAR128"
    frame_interval_us: int = 100_000  # 10 Hz


@dataclass
class PoseConfig:
    translation_m: tuple[float, float, float]
    rotation_xyzw: tuple[float, float, float, float]


@dataclass
class OpenCVPinholeConfig:
    """OpenCV pinhole parameters (matches sensorsim OpenCVPinholeCameraParam)."""

    focal_length: tuple[float, float]
    principal_point: tuple[float, float]
    radial: tuple[float, ...] = ()  # k1..k6
    tangential: tuple[float, ...] = ()  # p1, p2
    thin_prism: tuple[float, ...] = ()  # s1..s4


@dataclass
class OpenCVFisheyeConfig:
    focal_length: tuple[float, float]
    principal_point: tuple[float, float]
    radial: tuple[float, ...] = ()  # k1..k4
    max_angle: float | None = None


@dataclass
class LinearCdeConfig:
    linear_c: float
    linear_d: float
    linear_e: float


@dataclass
class FthetaConfig:
    principal_point: tuple[float, float]
    reference_poly: str  # Literal["pixel_to_angle", "angle_to_pixel"]
    pixeldist_to_angle: list[float] = field(default_factory=list)
    angle_to_pixeldist: list[float] = field(default_factory=list)
    max_angle: float | None = None
    linear_cde: LinearCdeConfig | None = None


@dataclass
class CameraIntrinsicsConfig:
    model: str  # Literal["opencv_pinhole", "opencv_fisheye", "ftheta"]
    opencv_pinhole: OpenCVPinholeConfig | None = None
    opencv_fisheye: OpenCVFisheyeConfig | None = None
    ftheta: FthetaConfig | None = None


@dataclass
class CameraDefinitionConfig:
    """Configuration for overriding camera definitions from sensorsim.

    Only `logical_id` is required - it identifies which camera to override.
    Other fields are optional; if not provided, the values from sensorsim
    are preserved.
    """

    logical_id: str
    # For NRE sensorsim, logical_id must match one of the existing cameras:
    #     - 'camera_cross_left_120fov'
    #     - 'camera_cross_right_120fov'
    #     - 'camera_front_tele_30fov'
    #     - 'camera_front_wide_120fov'
    rig_to_camera: PoseConfig | None = None
    intrinsics: CameraIntrinsicsConfig | None = None
    resolution_hw: tuple[int, int] | None = None
    # ShutterType is one of: [
    #     "ROLLING_TOP_TO_BOTTOM",
    #     "ROLLING_LEFT_TO_RIGHT",
    #     "ROLLING_BOTTOM_TO_TOP",
    #     "ROLLING_RIGHT_TO_LEFT",
    #     "GLOBAL"
    # ]
    shutter_type: str | None = None


class PhysicsUpdateMode(Enum):
    NONE = 0
    EGO_ONLY = 1
    ALL_ACTORS = 2


class RouteGeneratorType(Enum):
    MAP = 0
    RECORDED = 1


class RenderBundling(Enum):
    """Which sensorsim bundled-render RPC to use for a control step.

    NONE renders one ``render_rgb`` per camera; the others bundle all of a
    step's cameras into a single RPC (see sensorsim.proto).
    """

    NONE = "none"
    BATCH_RENDER_RGB = "batch_render_rgb"  # NRE batched render
    RENDER_AGGREGATED = "render_aggregated"  # ODL render+physics


@dataclass
class SimulationConfig:
    """
    Shared simulation parameters — applies to all scenes.
    """

    n_sim_steps: int = MISSING
    n_rollouts: int = MISSING

    control_timestep_us: int = 100_000
    pose_reporting_interval_us: int = 0  # 0 = no intermediate reporting
    force_gt_duration_us: int = 500_000  # 0.5s
    skip_driver_during_force_gt: bool = False

    # if true, we assert that each call to policy happens immediately after a frame has been
    # provided for each camera and the latest egomotion update. This flag does not modify
    # any parameters, only verifies that the config satisfies this condition (no user misconfiguration).
    # for extra information see the README.
    assert_zero_decision_delay: bool = False

    cameras: list[RuntimeCameraConfig] = field(
        default_factory=lambda: [RuntimeCameraConfig()]
    )

    # LiDARs are opt-in — drivers that need point clouds (e.g. OnePlanner)
    # populate this list; camera-only drivers leave it empty.
    lidars: list[RuntimeLidarConfig] = field(default_factory=list)

    # if None, the data will be pulled from the .usdz file
    vehicle: VehicleConfig | None = None

    physics_update_mode: PhysicsUpdateMode = PhysicsUpdateMode.NONE

    image_format: str = "jpeg"  # Literal["jpeg", "png"]
    # Rig/directory in ego-hoods to use for ego masking. If None, no ego masking will be done.
    ego_mask_rig_config_id: str | None = None
    planner_delay_us: int = (
        0  # models time delays from image capture to planner output to controller
    )

    route_generator_type: RouteGeneratorType = RouteGeneratorType.MAP
    route_start_offset_m: float = 0.0

    # Skip the first N microseconds of the recorded trajectory before starting
    # the rollout. 0 (default) reproduces the historical behavior of playing
    # from the very first recorded timestamp. Useful when the beginning of the
    # recording is uninteresting (parked/idle), or to supply enough
    # ego-history context for drivers like OnePlanner that condition on past
    # motion.
    trajectory_start_us_offset: int = 0

    # Whether to send optional messages to the driver
    send_recording_ground_truth: bool = False

    # Actors that appear for less than this amount of time will be dropped
    # before the simulation starts. Set to 0 to disable filtering.
    min_traffic_duration_us: int = 3_000_000  # 3 s

    # Which sensorsim bundled-render RPC to use (NONE = one render_rgb per camera).
    render_bundling: RenderBundling = RenderBundling.NONE


@dataclass
class SceneConfig:
    """Scene to simulate and number of rollouts to run for it."""

    scene_id: str = MISSING
    n_rollouts: int | None = None  # None = use SimulationConfig.n_rollouts


@dataclass
class UserEndpointConfig:
    """User-provided configuration for each of the endpoints"""

    driver: SingleUserEndpointConfig = MISSING
    physics: SingleUserEndpointConfig = MISSING
    trafficsim: SingleUserEndpointConfig = MISSING
    controller: SingleUserEndpointConfig = MISSING
    renderer: SingleUserEndpointConfig = MISSING

    sensorsim_cache_size: int | None = None  # Scene cache size for sensorsim
    startup_timeout_s: int = 2 * 60  # 2 minutes by default
    do_shutdown: bool = True


@dataclass
class UserSimulatorConfig:
    """The section of simulator config created manually by the user"""

    simulation_config: SimulationConfig = MISSING
    scenes: list[SceneConfig] = MISSING
    enable_autoresume: bool = False
    endpoints: UserEndpointConfig = MISSING

    smooth_trajectories: bool = True  # whether to smooth trajectories with cubic spline
    extra_cameras: list[CameraDefinitionConfig] = field(default_factory=list)

    # Number of worker processes for parallel rollout execution.
    # 1 = inline mode, all in one process, good for debugging
    # >1 = multi-worker mode with subprocess-based parallelism
    nr_workers: int = MISSING

    renderer: RendererConfig = MISSING

    # Runtime scene provider configuration.
    scene_provider: SceneProviderConfig = MISSING


@dataclass
class SimulatorConfig:
    """
    The entire simulator config consists of two parts, one provided by the user manually
    (`user`) and `network` which is likely autogenerated by the deployment system like wizard.
    """

    user: UserSimulatorConfig = MISSING
    network: NetworkSimulatorConfig = MISSING
